### ISSUE TITLE
readme improvements

### ISSUE THREAD

**Issue by jexp** [zmactep/hasbolt-sample-app#1]
Please add build instructions to readme.

If you have information on how to deploy the example to a cloud platform please add it too
also how you'd configure the neo4j-url

otherwise feel free to copy the other content from the existing movie-backend examples (or I can do it too).

**Comment by zmactep** [comment]
Hi, @jexp!

Thank you for the comment. I have updated README, so I think it is much more clear now. I have no experience with Heroku or similar cloud app platforms, so I'll be happy to get some help with such example.
